version: '3.6'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    hostname: kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  producer:
    image: "producer"
    build:
      context: .
      dockerfile: "dockerfiles/producer/Dockerfile"
    restart: on-failure
    environment:
      KAFKA_URL: "kafka:9093"
    depends_on:
      - kafka

  processor:
    image: "processor"
    build:
      context: .
      dockerfile: "dockerfiles/processor/Dockerfile"
    restart: on-failure
    environment:
      KAFKA_URL: "kafka:9093"
    depends_on:
      - kafka
